# Secret: sensitive data stored encoded (base64).
# WHY: Keeps passwords out of ConfigMaps, Dockerfiles, and Git.
# Kubernetes mounts them as env vars or files in the pod.
#
# NOTE: In production, use AWS Secrets Manager or Vault.
# Kubernetes Secrets are base64-encoded, NOT encrypted at rest by default.
# For this academic project, this is acceptable.
#
# Values are base64 encoded. To encode: echo -n "value" | base64
apiVersion: v1
kind: Secret
metadata:
  name: reservex-db-secret
  namespace: reservex
type: Opaque
data:
  # postgresql://reservex:REPLACE_ME_PASSWORD@postgres:5432/reservex
  DATABASE_URL: cG9zdGdyZXNxbDovL3Jlc2VydmV4OnJlc2VydmV4MTIzQHBvc3RncmVzOjU0MzIvcmVzZXJ2ZXg=
  POSTGRES_USER: cmVzZXJ2ZXg=
  POSTGRES_PASSWORD: cmVzZXJ2ZXgxMjM=
  POSTGRES_DB: cmVzZXJ2ZXg=
